### ISSUE TITLE
The description in cocoapods will cause misleading.

### ISSUE THREAD

**Issue by derjohng** [leoderbois/DragDropImageView#1]
The description in cocoapods will cause misleading.
https://cocoapods.org/?q=dragDropImageView

In this description, prefix of all methods is "dragAndDropImageView", and not "dragDropImageView". And strangely, they still can be compiled. However, they will NOT be called. I stuck in this issue until I find the description in github (here).

**Comment by leoderbois** [comment]
Hi @derjohng !
Yep, you are right, it look like i did not update the pod, I'll take sometime to update this pod soon as possible. I'm really sorry for the inconvenience ! 

"dragAndDropImageView" method not be called cause, the protocol change and is more "dragDropImageView"  "style.

**Comment by leoderbois** [comment]
I fix this, I make a push to trunk to update documentation and do some little fix. I remove Cocoalumberjack decency too.
